apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        dns_sd_configs:
          - names: ['product-service.microservices.svc.cluster.local']
            type: A
            port: 8081
      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        dns_sd_configs:
          - names: ['order-service.microservices.svc.cluster.local']
            type: A
            port: 8082
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        dns_sd_configs:
          - names: ['api-gateway.microservices.svc.cluster.local']
            type: A
            port: 8080
