server:
  port: 8082

spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: order-service

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
